[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.95.0",
    "mcp>=1.27.0",
    "python-dotenv>=1.2.2",
    "playwright>=1.44.0",
    "google-generativeai>=0.8.6",
    "aiohttp>=3.13.5",
    "google-genai>=1.73.1",
    "truststore>=0.10.4",
]
