[project]
name = "rag-llamaindex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "cohere>=5.20.7",
    "gradio>=6.9.0",
    "llama-index>=0.14.16",
    "llama-index-core>=0.14.16",
    "llama-index-embeddings-gemini>=0.4.2",
    "llama-index-embeddings-google-genai>=0.4.0",
    "llama-index-llms-gemini>=0.6.2",
    "llama-index-llms-google-genai>=0.8.7",
    "llama-index-vector-stores-pinecone>=0.7.1",
    "motor>=3.7.1",
    "pinecone>=7.0.0,<8.0.0",
    "pymongo>=4.16.0",
    "python-dotenv",
]
